# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd945bb6619195d49b07942811183cf38c2950f0ac40458c373348872c54e0c1fbf71f48667de06b7b6267e723d1a8d0a6c1b0c342b61ff5bfe6f976f9d2b360

test:
  secret_key_base: d4d808aba3d997d965a896e3120906b2f99ad1dd6b97b2e4be5bcef519263a2a4db9d8dfeeee2856c924f48c4aa489d13eee7b6bbf3fbf4dcc79a20a74e3f8d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
